"""
Django settings for book_library project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x^jv3-p_-fdlg3k%%tfq2_g0ambl06d_of5#q!3(2qkfmoccx$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '::1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
    "mozilla_django_oidc",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'book_library.middleware.OIDCRedirectURIMiddleware',
]

ROOT_URLCONF = 'book_library.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # можно добавить глобальные шаблоны, если нужно
        'APP_DIRS': True,  # <- обязательно True, чтобы Django искал templates внутри приложений
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'book_library.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

LOGOUT_REDIRECT_URL = '/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # старый логин/пароль
    "library.oidc_backend.KeycloakOIDCBackend",  # custom SSO backend для Keycloak
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# === KEYCLOAK OIDC (Настройки с твоими данными) ===

OIDC_RP_CLIENT_ID = "dev-api"
OIDC_RP_CLIENT_SECRET = "IYNTgfddrkcyjbdSwCk6PujRsRiDS9cG"

# Callback URL - ВАЖНО: должен быть зарегистрирован в Keycloak Client
OIDC_RP_CALLBACK_URL_NAME = "oidc_authentication_callback"

OIDC_OP_DISCOVERY_DOCUMENT_URL = "https://idp.nic.kz:8443/realms/dev-nic/.well-known/openid-configuration"
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/userinfo"
OIDC_OP_JWKS_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/certs"
OIDC_OP_LOGOUT_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/logout"

# Дополнительные параметры OIDC
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_IDP_SIGN_ALG = "RS256"
OIDC_USE_NONCE = True
OIDC_RENEW_ID_TOKEN_BEFORE_EXPIRY = True
OIDC_AUTH_REQUEST_SCOPES = ["openid", "profile", "email"]
OIDC_CREATE_USER = True  # Автоматически создавать пользователей при входе через OIDC
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True

# допускаем самоподписанные сертификаты
OIDC_VERIFY_SSL = False