"""
Django settings for book_library project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = 'django-insecure-x^jv3-p_-fdlg3k%%tfq2_g0ambl06d_of5#q!3(2qkfmoccx$'

DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '::1']



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
    "mozilla_django_oidc",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'book_library.middleware.OIDCRedirectURIMiddleware',
]

ROOT_URLCONF = 'book_library.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'book_library.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

LOGOUT_REDIRECT_URL = '/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "library.oidc_backend.KeycloakOIDCBackend",
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


OIDC_RP_CLIENT_ID = "dev-api"
OIDC_RP_CLIENT_SECRET = "IYNTgfddrkcyjbdSwCk6PujRsRiDS9cG"

OIDC_RP_CALLBACK_URL_NAME = "oidc_authentication_callback"

OIDC_OP_DISCOVERY_DOCUMENT_URL = "https://idp.nic.kz:8443/realms/dev-nic/.well-known/openid-configuration"
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/userinfo"
OIDC_OP_JWKS_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/certs"
OIDC_OP_LOGOUT_ENDPOINT = "https://idp.nic.kz:8443/realms/dev-nic/protocol/openid-connect/logout"

OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_IDP_SIGN_ALG = "RS256"
OIDC_USE_NONCE = True
OIDC_RENEW_ID_TOKEN_BEFORE_EXPIRY = True
OIDC_AUTH_REQUEST_SCOPES = ["openid", "profile", "email"]
OIDC_CREATE_USER = True
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True

OIDC_VERIFY_SSL = False